import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage { en, fr, ar }

class AppLocalizations extends ChangeNotifier {
  AppLanguage _currentLanguage = AppLanguage.ar; // Arabic by default

  AppLanguage get currentLanguage => _currentLanguage;
  bool get isRtl => _currentLanguage == AppLanguage.ar;

  /// Load saved language from SharedPreferences
  Future<void> loadSavedLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final savedLang = prefs.getString('app_language') ?? 'ar';
    switch (savedLang) {
      case 'en':
        _currentLanguage = AppLanguage.en;
        break;
      case 'fr':
        _currentLanguage = AppLanguage.fr;
        break;
      default:
        _currentLanguage = AppLanguage.ar;
    }
    notifyListeners();
  }

  /// Set and persist language
  Future<void> setLanguage(AppLanguage lang) async {
    _currentLanguage = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language', lang.name);
    notifyListeners();
  }

  String get(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }

  static final Map<AppLanguage, Map<String, String>> _translations = {
    AppLanguage.en: {
      // General
      'app_name': 'Fellahty',
      'welcome': 'Welcome!',
      'logout': 'Logout',
      'profile': 'Profile',
      'home': 'Home',
      'language': 'Language',
      'save': 'Save',
      'cancel': 'Cancel',
      'apply': 'Apply',
      'close': 'Close',
      'error': 'Error',
      'success': 'Success',
      'loading': 'Loading...',
      'no_data': 'No data available',
      'connect_grow': 'Connect • Grow • Succeed',

      // Auth
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'name': 'Full Name',
      'phone': 'Phone Number',
      'region': 'Region',
      'select_role': 'Select Your Role',
      'farmer': 'Farmer',
      'worker': 'Seasonal Worker',
      'equipment_owner': 'Equipment Owner',
      'no_account': "Don't have an account?",
      'have_account': 'Already have an account?',
      'register_here': 'Register here',
      'login_here': 'Login here',

      // Farmer
      'farmer_dashboard': 'Farmer Dashboard',
      'manage_jobs': 'Manage your agricultural jobs and workers',
      'active_jobs': 'Active Jobs',
      'applications': 'Applications',
      'post_job': 'Post Job',
      'post_new_job': 'Post a New Job',
      'looking_workers': 'Looking for seasonal workers?',
      'review_applications': 'Review Applications',
      'check_workers': 'Check workers who applied to your jobs',
      'find_equipment': 'Find Equipment',
      'rent_tools': 'Need to rent a tractor or tools?',
      'quick_actions': 'Quick Actions',
      'my_jobs': 'My Jobs',
      'my_posted_jobs': 'My Posted Jobs',
      'job_details': 'Job Details',
      'job_title': 'Job Title',
      'job_title_hint': 'e.g. Orange Harvesting, Tractor Driver',
      'workers_needed': 'Workers Needed',
      'salary_per_day': 'Salary / Day',
      'location': 'Location',
      'location_hint': 'e.g. Agadir Region, Block 4',
      'start_date': 'Start Date',
      'select_start_date': 'Select Start Date',
      'job_posted': 'Job posted successfully!',
      'close_job': 'Close Job?',
      'close_job_confirm': 'Are you sure you want to mark this job as closed?',
      'no_applications': 'No applications yet for this job.',
      'no_jobs_posted': 'No jobs posted yet',

      // Worker
      'worker_dashboard': 'Worker Dashboard',
      'find_work': 'Find flexible agricultural work near you',
      'current_jobs': 'Current Jobs',
      'score': 'Score',
      'browse_jobs': 'Browse New Jobs',
      'new_opportunities': 'New opportunities are waiting',
      'view_applications': 'View Applications',
      'check_status': 'Check the status of your jobs',
      'find_jobs': 'Find Jobs',
      'available_jobs': 'Available Jobs',
      'apply_now': 'Apply',
      'applied': 'Applied!',
      'already_applied': 'Already Applied',
      'no_jobs': 'No open jobs available',
      'my_applications': 'My Applications',
      'pending': 'Pending',
      'accepted': 'Accepted',
      'rejected': 'Rejected',

      // Equipment
      'equipment_dashboard': 'Equipment Dashboard',
      'manage_equipment': 'Manage your agricultural equipment rentals',
      'total_fleet': 'Total Fleet',
      'rented_out': 'Rented Out',
      'add_equipment': 'Add',
      'add_new_equipment': 'Add New Equipment',
      'list_equipment': 'List another tractor or tool',
      'my_fleet': 'My Fleet',
      'equipment_type': 'Equipment Type',
      'equipment_type_hint': 'e.g. Tractor, Harvester, Plow',
      'rental_price': 'Rental Price / Day',
      'description': 'Description',
      'description_hint': 'Provide details about condition, capabilities, etc.',
      'available': 'AVAILABLE',
      'rented': 'RENTED',
      'equipment_added': 'Equipment added successfully!',
      'no_equipment': 'No equipment added yet',
      'add_photos': 'Add Photos',
      'tap_to_add_photo': 'Tap to add equipment photos',

      // Profile
      'my_profile': 'My Profile',
      'email_address': 'Email Address',
      'phone_number': 'Phone Number',
      'overall_score': 'Overall Score',
      'no_ratings': 'No ratings yet',
      'edit_profile': 'EDIT PROFILE',

      // Rating
      'rate_worker': 'Rate Worker',
      'submit_rating': 'Submit Rating',
      'reject': 'Reject',
      'accept': 'Accept',
      'rating': 'Rating',

      // Wallet
      'my_wallet': 'My Wallet',
      'total_balance': 'Total Balance',
      'recent_transactions': 'Recent Transactions',
      'no_transactions_yet': 'No transactions yet',
      'manage_funds': 'Manage your balance',
      'check_earnings': 'Check your earnings',
      'add_balance_test': 'Add 500 MAD (Test)',

      // Job Completion
      'mark_completed': 'Mark Completed',
      'waiting_farmer_confirmation': 'Waiting for farmer to confirm',
      'job_finished_paid': 'Job Finished & Paid',
      'confirm_and_pay': 'Confirm & Pay',
      'waiting_worker_finish': 'Waiting for worker to finish...',
      'payment_success': 'Payment processed successfully!',

      // Notifications
      'new_job_available': 'New Job Alert!',
      'new_rental_request': 'New Rental Request',
      'rental_requested': 'Rental request sent!',

      // Rental
      'rental_requests': 'Rental Requests',
      'manage_bookings': 'Manage your equipment bookings',
      'rent_now': 'Rent Now',
      'renter': 'Renter',
      'price': 'Price',
      'no_rentals': 'No rental requests yet',

      // Create Job
      'post_a_new_job': 'Post a New Job',
      'select_date': 'Select Start Date',

      // Admin
      'admin_panel': 'Admin Panel',
      'app_statistics': 'App Statistics',
      'total_revenue': 'Total App Revenue (MAD)',
      'from_commissions': 'From all commissions',
      'system_reports': 'System Reports',

      // Daily System
      'duration_days': 'Duration (Days)',
      'days': 'days',
      'day': 'Day',
      'daily_tracking': 'Daily Tracking',
      'daily_payment': 'Payment is daily',
      'total_price': 'Total Price',
      'enter_code': 'Enter Code',
      'enter_confirmation_code': 'Enter Confirmation Code',
      'enter_code_hint': 'Ask the farmer for today\'s code',
      'enter_code_hint_owner': 'Ask the farmer for today\'s code',
      'code': 'Code',
      'code_accepted': 'Code accepted! ✓',
      'code_wrong': 'Wrong code. Try again.',
      'confirm': 'Confirm',
      'paid': 'Paid ✓',
      'absence_reported': 'Absence Reported',
      'report_absence': 'Report Absence',
      'worker_confirmed': 'Worker confirmed work',
      'owner_confirmed': 'Owner confirmed delivery',
      'waiting_worker_code': 'Waiting for worker to enter code...',
      'waiting_owner_code': 'Waiting for owner to enter code...',
      'rate_before_pay': 'Rate before confirming payment',
      'rate_equipment': 'Rate Equipment',
      'active': 'Active',
      'my_rentals': 'My Rentals',
      'clear_data': 'Clear Data',
      'data_cleared': 'Data cleared successfully',

      // Support
      'support': 'Support',
      'support_title': 'How can we help?',
      'support_subtitle': 'Contact our support team for any questions or issues',
      'email_support': 'Email Support',
      'phone_support': 'Phone Support',
      'whatsapp_support': 'Chat with us on WhatsApp',
      'faq': 'Frequently Asked Questions',
      'faq_q1': 'How does the daily payment system work?',
      'faq_a1': 'At the end of each work day, the farmer gives the worker a 4-digit code. The worker enters it in the app to confirm their work. Then the farmer confirms and pays for that day.',
      'faq_q2': 'How are commissions calculated?',
      'faq_a2': 'For salaries above 100 MAD/day, the app takes 15% commission. Below 100 MAD/day, a flat 20 MAD fee applies.',
      'faq_q3': 'What if there is a dispute?',
      'faq_a3': 'Contact our support team via email or WhatsApp. We will help resolve any disputes between parties.',
      
      // Admin, Delete, Cancel
      'confirm_delete': 'Are you sure you want to delete this?',
      'cancel_application': 'Cancel Application',
      'cancel_application_confirm': 'Are you sure you want to cancel this application?',
      'cancel_rental': 'Cancel Rental',
      'cancel_rental_confirm': 'Are you sure you want to cancel this rental request?',
      'success': 'Action completed successfully',
      'ban_user': 'Ban User',
      'unban_user': 'Unban User',
      'no_jobs': 'No jobs found',
      'no_equipment': 'No equipment found',
      'retry': 'Retry',
      'finish_work': 'Finish Work',
      'finish_rental': 'Finish Rental',
      'finish_work_confirm': 'Are you sure you have finished this work?',
    },

    AppLanguage.fr: {
      'app_name': 'Fellahty',
      'welcome': 'Bienvenue !',
      'logout': 'Déconnexion',
      'profile': 'Profil',
      'home': 'Accueil',
      'language': 'Langue',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'apply': 'Postuler',
      'close': 'Fermer',
      'error': 'Erreur',
      'success': 'Succès',
      'loading': 'Chargement...',
      'no_data': 'Aucune donnée disponible',
      'connect_grow': 'Connecter • Grandir • Réussir',

      'login': 'Connexion',
      'register': "S'inscrire",
      'email': 'Email',
      'password': 'Mot de passe',
      'name': 'Nom complet',
      'phone': 'Numéro de téléphone',
      'region': 'Région',
      'select_role': 'Choisissez votre rôle',
      'farmer': 'Agriculteur',
      'worker': 'Ouvrier saisonnier',
      'equipment_owner': "Propriétaire d'équipement",
      'no_account': "Vous n'avez pas de compte ?",
      'have_account': 'Vous avez déjà un compte ?',
      'register_here': "S'inscrire ici",
      'login_here': 'Se connecter ici',

      'farmer_dashboard': "Tableau de bord Agriculteur",
      'manage_jobs': 'Gérez vos emplois agricoles et vos ouvriers',
      'active_jobs': 'Emplois actifs',
      'applications': 'Candidatures',
      'post_job': 'Publier',
      'post_new_job': 'Publier un nouvel emploi',
      'looking_workers': 'Vous cherchez des ouvriers saisonniers ?',
      'review_applications': 'Examiner les candidatures',
      'check_workers': 'Voir les ouvriers qui ont postulé',
      'find_equipment': 'Trouver du matériel',
      'rent_tools': 'Besoin de louer un tracteur ou des outils ?',
      'quick_actions': 'Actions rapides',
      'my_jobs': 'Mes emplois',
      'my_posted_jobs': 'Mes emplois publiés',
      'job_details': "Détails de l'emploi",
      'job_title': "Titre de l'emploi",
      'job_title_hint': 'ex. Récolte des oranges, Conducteur de tracteur',
      'workers_needed': "Nombre d'ouvriers",
      'salary_per_day': 'Salaire / Jour',
      'location': 'Lieu',
      'location_hint': 'ex. Région Agadir, Bloc 4',
      'start_date': 'Date de début',
      'select_start_date': 'Sélectionner la date de début',
      'job_posted': 'Emploi publié avec succès !',
      'close_job': 'Fermer cet emploi ?',
      'close_job_confirm': 'Êtes-vous sûr de vouloir fermer cet emploi ?',
      'no_applications': 'Aucune candidature pour cet emploi.',
      'no_jobs_posted': 'Aucun emploi publié',

      'worker_dashboard': 'Tableau de bord Ouvrier',
      'find_work': 'Trouvez du travail agricole flexible près de chez vous',
      'current_jobs': 'Emplois en cours',
      'score': 'Note',
      'browse_jobs': 'Parcourir les emplois',
      'new_opportunities': 'De nouvelles opportunités vous attendent',
      'view_applications': 'Voir les candidatures',
      'check_status': 'Vérifiez le statut de vos candidatures',
      'find_jobs': 'Chercher',
      'available_jobs': 'Emplois disponibles',
      'apply_now': 'Postuler',
      'applied': 'Postulé !',
      'already_applied': 'Déjà postulé',
      'no_jobs': 'Aucun emploi disponible',
      'my_applications': 'Mes candidatures',
      'pending': 'En attente',
      'accepted': 'Accepté',
      'rejected': 'Refusé',

      'equipment_dashboard': "Tableau de bord Équipement",
      'manage_equipment': 'Gérez vos locations de matériel agricole',
      'total_fleet': 'Flotte totale',
      'rented_out': 'En location',
      'add_equipment': 'Ajouter',
      'add_new_equipment': 'Ajouter un équipement',
      'list_equipment': 'Ajouter un tracteur ou un outil',
      'my_fleet': 'Ma flotte',
      'equipment_type': "Type d'équipement",
      'equipment_type_hint': 'ex. Tracteur, Moissonneuse, Charrue',
      'rental_price': 'Prix de location / Jour',
      'description': 'Description',
      'description_hint': 'Détails sur l\'état, les capacités, etc.',
      'available': 'DISPONIBLE',
      'rented': 'LOUÉ',
      'equipment_added': 'Équipement ajouté avec succès !',
      'no_equipment': 'Aucun équipement ajouté',
      'add_photos': 'Ajouter des photos',
      'tap_to_add_photo': 'Appuyez pour ajouter des photos',

      'my_profile': 'Mon profil',
      'email_address': 'Adresse email',
      'phone_number': 'Numéro de téléphone',
      'overall_score': 'Note globale',
      'no_ratings': 'Pas encore de note',
      'edit_profile': 'MODIFIER LE PROFIL',

      'rate_worker': "Noter l'ouvrier",
      'submit_rating': 'Soumettre la note',
      'reject': 'Refuser',
      'accept': 'Accepter',
      'rating': 'Note',

      // Wallet
      'my_wallet': 'Mon Portefeuille',
      'total_balance': 'Solde Total',
      'recent_transactions': 'Transactions Récentes',
      'no_transactions_yet': 'Aucune transaction',
      'manage_funds': 'Gérer votre solde',
      'check_earnings': 'Vérifier vos gains',
      'add_balance_test': 'Ajouter 500 MAD (Test)',

      // Job Completion
      'mark_completed': 'Marquer comme terminé',
      'waiting_farmer_confirmation': "En attente de confirmation de l'agriculteur",
      'job_finished_paid': 'Travail terminé et payé',
      'confirm_and_pay': 'Confirmer et payer',
      'waiting_worker_finish': "En attente que l'ouvrier termine...",
      'payment_success': 'Paiement effectué avec succès !',

      // Notifications
      'new_job_available': 'Nouvelle offre !',
      'new_rental_request': 'Nouvelle demande de location',
      'rental_requested': 'Demande de location envoyée !',

      // Rental
      'rental_requests': 'Demandes de Location',
      'manage_bookings': 'Gérer vos réservations',
      'rent_now': 'Louer Maintenant',
      'renter': 'Locataire',
      'price': 'Prix',
      'no_rentals': 'Aucune demande de location',

      // Create Job
      'post_a_new_job': 'Publier un nouvel emploi',
      'select_date': 'Sélectionner la date de début',

      // Admin
      'admin_panel': "Panneau d'Administration",
      'app_statistics': 'Statistiques',
      'total_revenue': "Revenu Total de l'App (MAD)",
      'from_commissions': 'De toutes les commissions',
      'system_reports': 'Rapports Système',

      // Daily System
      'duration_days': 'Durée (Jours)',
      'days': 'jours',
      'day': 'Jour',
      'daily_tracking': 'Suivi Quotidien',
      'daily_payment': 'Paiement quotidien',
      'total_price': 'Prix Total',
      'enter_code': 'Entrer le Code',
      'enter_confirmation_code': 'Entrer le Code de Confirmation',
      'enter_code_hint': "Demandez le code du jour à l'agriculteur",
      'enter_code_hint_owner': "Demandez le code du jour à l'agriculteur",
      'code': 'Code',
      'code_accepted': 'Code accepté ! ✓',
      'code_wrong': 'Code incorrect. Réessayez.',
      'confirm': 'Confirmer',
      'paid': 'Payé ✓',
      'absence_reported': 'Absence Signalée',
      'report_absence': 'Signaler Absence',
      'worker_confirmed': "L'ouvrier a confirmé son travail",
      'owner_confirmed': 'Le propriétaire a confirmé la livraison',
      'waiting_worker_code': "En attente que l'ouvrier entre le code...",
      'waiting_owner_code': 'En attente que le propriétaire entre le code...',
      'rate_before_pay': 'Notez avant de confirmer le paiement',
      'rate_equipment': "Noter l'équipement",
      'active': 'Actif',
      'my_rentals': 'Mes Locations',
      'clear_data': 'Effacer les données',
      'data_cleared': 'Données effacées avec succès',

      // Support
      'support': 'Support',
      'support_title': 'Comment pouvons-nous aider ?',
      'support_subtitle': 'Contactez notre équipe pour toute question',
      'email_support': 'Support par Email',
      'phone_support': 'Support Téléphonique',
      'whatsapp_support': 'Discutez avec nous sur WhatsApp',
      'faq': 'Questions Fréquentes',
      'faq_q1': 'Comment fonctionne le paiement quotidien ?',
      'faq_a1': "L'agriculteur donne un code de 4 chiffres à l'ouvrier chaque jour. L'ouvrier le saisit dans l'app pour confirmer.",
      'faq_q2': 'Comment sont calculées les commissions ?',
      'faq_a2': 'Au-dessus de 100 MAD/jour: 15%. En dessous: 20 MAD fixe.',
      'faq_q3': 'Que faire en cas de litige ?',
      'faq_a3': 'Contactez notre support par email ou WhatsApp.',

      // Admin, Delete, Cancel
      'confirm_delete': 'Êtes-vous sûr de vouloir supprimer ceci ?',
      'cancel_application': 'Annuler la demande',
      'cancel_application_confirm': 'Êtes-vous sûr de vouloir annuler cette demande ?',
      'cancel_rental': 'Annuler la location',
      'cancel_rental_confirm': 'Êtes-vous sûr de vouloir annuler cette demande de location ?',
      'success': 'Action effectuée avec succès',
      'ban_user': "Bannir l'utilisateur",
      'unban_user': "Débannir l'utilisateur",
      'no_jobs': 'Aucun travail trouvé',
      'no_equipment': 'Aucun équipement trouvé',
      'retry': 'Réessayer',
      'finish_work': 'Terminer le travail',
      'finish_rental': 'Terminer la location',
      'finish_work_confirm': 'Êtes-vous sûr d\'avoir terminé ce travail ?',
    },

    AppLanguage.ar: {
      'app_name': 'فلاحتي',
      'welcome': 'مرحباً!',
      'logout': 'تسجيل الخروج',
      'profile': 'الملف الشخصي',
      'home': 'الرئيسية',
      'language': 'اللغة',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'apply': 'تقديم',
      'close': 'إغلاق',
      'error': 'خطأ',
      'success': 'نجاح',
      'loading': 'جاري التحميل...',
      'no_data': 'لا توجد بيانات',
      'connect_grow': 'تواصل • ازرع • انجح',

      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'name': 'الاسم الكامل',
      'phone': 'رقم الهاتف',
      'region': 'المنطقة',
      'select_role': 'اختر دورك',
      'farmer': 'فلاح',
      'worker': 'عامل موسمي',
      'equipment_owner': 'صاحب معدات',
      'no_account': 'ليس لديك حساب؟',
      'have_account': 'لديك حساب بالفعل؟',
      'register_here': 'سجل هنا',
      'login_here': 'سجل الدخول هنا',

      'farmer_dashboard': 'لوحة تحكم الفلاح',
      'manage_jobs': 'قم بإدارة أعمالك الزراعية والعمال',
      'active_jobs': 'وظائف نشطة',
      'applications': 'طلبات التوظيف',
      'post_job': 'نشر وظيفة',
      'post_new_job': 'نشر وظيفة جديدة',
      'looking_workers': 'تبحث عن عمال موسميين؟',
      'review_applications': 'مراجعة الطلبات',
      'check_workers': 'تحقق من العمال الذين تقدموا لوظائفك',
      'find_equipment': 'البحث عن معدات',
      'rent_tools': 'هل تحتاج لاستئجار جرار أو أدوات؟',
      'quick_actions': 'إجراءات سريعة',
      'my_jobs': 'وظائفي',
      'my_posted_jobs': 'الوظائف المنشورة',
      'job_details': 'تفاصيل الوظيفة',
      'job_title': 'عنوان الوظيفة',
      'job_title_hint': 'مثال: جني البرتقال، سائق جرار',
      'workers_needed': 'عدد العمال المطلوبين',
      'salary_per_day': 'الأجر اليومي',
      'location': 'الموقع',
      'location_hint': 'مثال: منطقة أكادير، القطعة 4',
      'start_date': 'تاريخ البداية',
      'select_start_date': 'اختر تاريخ البداية',
      'job_posted': 'تم نشر الوظيفة بنجاح!',
      'close_job': 'إغلاق الوظيفة؟',
      'close_job_confirm': 'هل أنت متأكد من إغلاق هذه الوظيفة؟',
      'no_applications': 'لا توجد طلبات لهذه الوظيفة بعد.',
      'no_jobs_posted': 'لم تنشر أي وظائف بعد',

      'worker_dashboard': 'لوحة تحكم العامل',
      'find_work': 'ابحث عن عمل زراعي مرن بالقرب منك',
      'current_jobs': 'وظائف حالية',
      'score': 'التقييم',
      'browse_jobs': 'تصفح الوظائف',
      'new_opportunities': 'فرص جديدة بانتظارك',
      'view_applications': 'عرض الطلبات',
      'check_status': 'تحقق من حالة طلباتك',
      'find_jobs': 'البحث',
      'available_jobs': 'الوظائف المتاحة',
      'apply_now': 'تقديم',
      'applied': 'تم التقديم!',
      'already_applied': 'تم التقديم مسبقاً',
      'no_jobs': 'لا توجد وظائف متاحة',
      'my_applications': 'طلباتي',
      'pending': 'قيد الانتظار',
      'accepted': 'مقبول',
      'rejected': 'مرفوض',

      'equipment_dashboard': 'لوحة تحكم المعدات',
      'manage_equipment': 'قم بإدارة تأجير معداتك الزراعية',
      'total_fleet': 'إجمالي المعدات',
      'rented_out': 'مؤجرة',
      'add_equipment': 'إضافة',
      'add_new_equipment': 'إضافة معدات جديدة',
      'list_equipment': 'أضف جراراً أو أداة',
      'my_fleet': 'معداتي',
      'equipment_type': 'نوع المعدات',
      'equipment_type_hint': 'مثال: جرار، حصادة، محراث',
      'rental_price': 'سعر الإيجار / يوم',
      'description': 'الوصف',
      'description_hint': 'تفاصيل عن الحالة والإمكانيات...',
      'available': 'متاح',
      'rented': 'مؤجر',
      'equipment_added': 'تمت إضافة المعدات بنجاح!',
      'no_equipment': 'لم تتم إضافة معدات بعد',
      'add_photos': 'إضافة صور',
      'tap_to_add_photo': 'اضغط لإضافة صور المعدات',

      'my_profile': 'ملفي الشخصي',
      'email_address': 'البريد الإلكتروني',
      'phone_number': 'رقم الهاتف',
      'overall_score': 'التقييم العام',
      'no_ratings': 'لا يوجد تقييم بعد',
      'edit_profile': 'تعديل الملف',

      'rate_worker': 'تقييم العامل',
      'submit_rating': 'إرسال التقييم',
      'reject': 'رفض',
      'accept': 'قبول',
      'rating': 'التقييم',

      // Wallet
      'my_wallet': 'محفظتي',
      'total_balance': 'الرصيد الإجمالي',
      'recent_transactions': 'المعاملات الأخيرة',
      'no_transactions_yet': 'لا توجد معاملات بعد',
      'manage_funds': 'إدارة رصيدك',
      'check_earnings': 'تحقق من أرباحك',
      'add_balance_test': 'إضافة 500 درهم (تجربة)',

      // Job Completion
      'mark_completed': 'إنهاء العمل',
      'waiting_farmer_confirmation': 'في انتظار تأكيد الفلاح',
      'job_finished_paid': 'تم إنهاء العمل والدفع ✓',
      'confirm_and_pay': 'تأكيد والدفع',
      'waiting_worker_finish': 'في انتظار إنهاء العامل للعمل...',
      'payment_success': 'تمت عملية الدفع بنجاح!',

      // Notifications
      'new_job_available': 'فرصة عمل جديدة!',
      'new_rental_request': 'طلب كراء جديد',
      'rental_requested': 'تم إرسال طلب الكراء!',

      // Rental
      'rental_requests': 'طلبات الكراء',
      'manage_bookings': 'إدارة حجوزات معداتك',
      'rent_now': 'استئجار الآن',
      'renter': 'المستأجر',
      'price': 'الثمن',
      'no_rentals': 'لا توجد طلبات كراء بعد',

      // Create Job
      'post_a_new_job': 'نشر وظيفة جديدة',
      'select_date': 'اختر تاريخ البداية',

      // Admin
      'admin_panel': 'لوحة الإدارة',
      'app_statistics': 'إحصائيات التطبيق',
      'total_revenue': 'إجمالي مداخيل التطبيق (درهم)',
      'from_commissions': 'من جميع العمولات',
      'system_reports': 'تقارير النظام',

      // Daily System
      'duration_days': 'المدة (أيام)',
      'days': 'أيام',
      'day': 'يوم',
      'daily_tracking': 'التتبع اليومي',
      'daily_payment': 'الدفع يومي',
      'total_price': 'المبلغ الإجمالي',
      'enter_code': 'أدخل الرمز',
      'enter_confirmation_code': 'أدخل رمز التأكيد',
      'enter_code_hint': 'اطلب رمز اليوم من الفلاح',
      'enter_code_hint_owner': 'اطلب رمز اليوم من المستأجر',
      'code': 'الرمز',
      'code_accepted': 'تم قبول الرمز! ✓',
      'code_wrong': 'رمز خاطئ. حاول مرة أخرى.',
      'confirm': 'تأكيد',
      'paid': 'مدفوع ✓',
      'absence_reported': 'تم الإبلاغ عن الغياب',
      'report_absence': 'إبلاغ عن غياب',
      'worker_confirmed': 'أكد العامل عمله',
      'owner_confirmed': 'أكد المالك التسليم',
      'waiting_worker_code': 'في انتظار إدخال العامل للرمز...',
      'waiting_owner_code': 'في انتظار إدخال المالك للرمز...',
      'rate_before_pay': 'قيم قبل تأكيد الدفع',
      'rate_equipment': 'تقييم المعدات',
      'active': 'نشط',
      'my_rentals': 'إيجاراتي',
      'clear_data': 'مسح البيانات',
      'data_cleared': 'تم مسح البيانات بنجاح',

      // Support
      'support': 'الدعم',
      'support_title': 'كيف يمكننا مساعدتك؟',
      'support_subtitle': 'تواصل مع فريق الدعم لأي سؤال أو مشكلة',
      'email_support': 'الدعم عبر البريد الإلكتروني',
      'phone_support': 'الدعم الهاتفي',
      'whatsapp_support': 'تحدث معنا عبر واتساب',
      'faq': 'الأسئلة الشائعة',
      'faq_q1': 'كيف يعمل نظام الدفع اليومي؟',
      'faq_a1': 'في نهاية كل يوم، يعطي الفلاح رمزاً من 4 أرقام للعامل. العامل يدخله في التطبيق لتأكيد عمله، ثم الفلاح يؤكد ويدفع.',
      'faq_q2': 'كيف تحسب العمولات؟',
      'faq_a2': 'أكثر من 100 درهم/يوم: 15%. أقل من 100 درهم/يوم: 20 درهم ثابتة.',
      'faq_q3': 'ماذا في حالة خلاف؟',
      'faq_a3': 'تواصل مع فريق الدعم عبر البريد الإلكتروني أو واتساب.',

      // Admin, Delete, Cancel
      'confirm_delete': 'هل أنت متأكد أنك تريد حذف هذا؟',
      'cancel_application': 'إلغاء الطلب',
      'cancel_application_confirm': 'هل أنت متأكد أنك تريد إلغاء هذا الطلب؟',
      'cancel_rental': 'إلغاء الكراء',
      'cancel_rental_confirm': 'هل أنت متأكد أنك تريد إلغاء طلب الكراء هذا؟',
      'success': 'تمت العملية بنجاح',
      'ban_user': 'حظر المستخدم',
      'unban_user': 'إلغاء حظر المستخدم',
      'no_jobs': 'لا توجد وظائف',
      'no_equipment': 'لا توجد معدات',
      'retry': 'إعادة المحاولة',
      'finish_work': 'إنهاء العمل',
      'finish_rental': 'إنهاء الكراء',
      'finish_work_confirm': 'هل أنت متأكد من إنهاء هذا العمل؟',
    },
  };
}

// Global instance
final appLocale = AppLocalizations();
